### ISSUE TITLE
Allow user to change default GitHub URL

### ISSUE THREAD

**Issue by riordan** [jupyterlab/pull-requests#11]
This is an unbelievably useful extension for making notebook code review more accessible.

We'd love to use it with our corporate Github system, which has an API identical to that of public GitHub. In order to use this, we'd need to be able to [set the base URL for Github](https://github.com/jupyterlab/pull-requests/blob/6493c6166acdc67e921bc42f106a55fe895066cf/jupyterlab_pullrequests/github_manager.py#L11) as a configurable parameter from the Jupyter Configuration file.

**Comment by jaipreet-s** [comment]
Hi @riordan - That would be a great enhancement. I'd be fine using an environment variable for `GITHUB_BASE_URL` which would override the default public GitHub API URL. 

PRs welcome :-)

**Comment by fcollonval** [comment]
Fixes in #16
