### ISSUE TITLE
Jupyterlab failed to build after installing pull-requests

### ISSUE THREAD

**Issue by issafuad** [jupyterlab/pull-requests#13]
Given that jupyterlab >2.0 is not compatible with pull-requests. I have jupyterlab 1.0.0
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.15.0
ipykernel        : 5.3.0
jupyter client   : 6.1.3
jupyter lab      : 1.0.0
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.0.7
traitlets        : 4.3.3

After running
jupyter labextension install @jupyterlab/pullrequests

I get 

Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-6twlehu6.log

When checking the log file, I can see

LabBuildApp] Building in /Users/fuadissa/miniconda3/share/jupyter/lab
[LabBuildApp] Node v14.1.0

[LabBuildApp] Building jupyterlab assets
[LabBuildApp] WARNING | 
"nbdime-jupyterlab@2.0.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab             Extension      Package
>=1.0.0 <2.0.0         >=2.0.0 <3.0.0 @jupyterlab/apputils
>=3.0.0 <4.0.0         >=4.0.0 <5.0.0 @jupyterlab/coreutils
>=1.0.0 <2.0.0         >=2.0.0 <3.0.0 @jupyterlab/notebook
>=1.0.0 <2.0.0         >=2.0.0 <3.0.0 @jupyterlab/rendermime
>=4.0.0 <5.0.0         >=5.0.0 <6.0.0 @jupyterlab/services

[LabBuildApp] > node /Users/fuadissa/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 149.57s.

[LabBuildApp] > node /Users/fuadissa/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.15.2
$ /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] > node /Users/fuadissa/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 10.61s.

[LabBuildApp] > node /Users/fuadissa/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build
[LabBuildApp] yarn run v1.15.2
$ webpack
ModuleNotFoundError: Module not found: Error: Can't resolve 'd3-color' in '/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/pullrequests/lib/components/diff'
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:821:10
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:397:22
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve 'd3-color' in '/Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/pullrequests/lib/components/diff'
  Parsed request is a module
  using description file: /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/pullrequests/package.json (relative path: ./lib/components/diff)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/pullrequests/lib/components/diff/node_modules doesn't exist or is not a directory
      /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/pullrequests/lib/components/node_modules doesn't exist or is not a directory
      /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/pullrequests/lib/node_modules doesn't exist or is not a directory
      /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/pullrequests/node_modules doesn't exist or is not a directory
      /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/node_modules doesn't exist or is not a directory
      /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      /Users/fuadissa/miniconda3/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /Users/fuadissa/miniconda3/share/jupyter/node_modules doesn't exist or is not a directory
      /Users/fuadissa/miniconda3/share/node_modules doesn't exist or is not a directory
      /Users/fuadissa/miniconda3/node_modules doesn't exist or is not a directory
      /Users/fuadissa/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules
        using description file: /Users/fuadissa/miniconda3/share/jupyter/lab/staging/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/fuadissa/miniconda3/share/jupyter/lab/staging/package.json (relative path: ./node_modules/d3-color)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/d3-color doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/d3-color.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/d3-color.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/d3-color.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/d3-color.json doesn't exist
            as directory
              /Users/fuadissa/miniconda3/share/jupyter/lab/staging/node_modules/d3-color doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/Users/fuadissa/miniconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/Users/fuadissa/miniconda3/lib/python3.7/site-packages/jupyterlab/labapp.py", line 80, in start
    command=command, logger=self.log)

[LabBuildApp]   File "/Users/fuadissa/miniconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 373, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/Users/fuadissa/miniconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 566, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

**Comment by blink1073** [comment]
The previous version had some brittle dependencies, I'm pushing this forward for JLab 2.0: https://github.com/jupyterlab/pull-requests/pull/14

**Comment by fcollonval** [comment]
Closing as it works for JupyterLab 2 (JLab 3 is coming shortly).

Please open a new issue if there is still some issue with installation.
