### ISSUE TITLE
Support JupyterLab 3 (and 2?)

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/pull-requests#27]
Over on #16 we discussed getting the feature updates landed and then moving forward on supporting JupyterLab 3. 

## Prior art

Much of the packaging plumbing is visible on a [self-PR](https://github.com/bollwyvl/pull-requests/pull/1). It could drop the monaco stuff, as it adds a fair amount of complexity, but much of the other stuff is fine (more aggressive linting/compiler options).

## Alternatives

- maintain two branches
  - start a new 3.x branch for JupyterLab 3
    - accept features and bugfixe PRs here
  - start a new 2.x branch for JupyterLab 2
    - accept bugfix PRs here
- somehow support releasing for both from one codebase

## Challenges
While the single branch plan sounds like the "happy path," I am concerned about:
- testing
  - would need `tox`/`nox` (or a lot of complexity) locally
- features
  - inability to take advantage of newer features on Lab 3.x that aren't backported to 2.x as they emerge
    - maybe identity, settings 
- documentation complexity
  - `pip install` and link to _for JupyterLab 2.x see the `2.x` branch_ vs
  - `pip install` _but if you're on JupyterLab 3, then do these five things..._

**Comment by bollwyvl** [comment]
> we use two branches

great, since these fates of these two should be intertwined, that makes a lot of sense.

> GitHub action on release creation event. 

Yeah, I feel like this is usually not worth the automation. I'm a big fan, however, of doing a _single_ CI build of release artifacts, and only testing against them, rather than in-tree code, and making them available in a single release bundle. Then moving it up to github, pip, npm, whatever, isn't really that hard, as these things are _good_ at handling tarballs :P

> move forward

Well: perhaps a GitHub project makes sense? We've got a a fair number of issues, but _some_ form of prioritization/roadmap would be helpful. Once there's a list of bite-sized things to tackle in a reasonable order, we can split up the work more effectively without as much timezone fatigue.

**Comment by bollwyvl** [comment]
Project is set up:
https://github.com/jupyterlab/pull-requests/projects/1?add_cards_query=is%3Aopen

_To Do_ is not in any _particular_ order, beyond my personal feeling that schema and _some_ some flavor of frontend testing are important to landing additional features.

Will hoist some of the stuff discussed here (e.g. release engineering).

**Comment by fcollonval** [comment]
Thanks a lot @bollwyvl

**Comment by bollwyvl** [comment]
Ok, I think all the work is done now with the two branches, and the up-front docs in the README!
